### PR TITLE
fix travis release branch conditonal

### PR DESCRIPTION
**Pull request by ggilmore**

### CODE REVIEW

**Comment by felixfbecker** [comment]
@ggilmore could you give a PR description? What problem does this fix?

**Comment by ggilmore** [comment]
When you push a tag `v.X.X.X` to github, Travis sees the branch name as `v.X.X.X`, not `master`. This means that the release job for the binaries will never run. 

See https://github.com/travis-ci/travis-ci/issues/8518

**Comment by felixfbecker** [comment]
And why do we need to build the Docker images on tags? Since every tag is for a commit, that same commit will have already been build, so wouldn't we build it twice?

**Comment by felixfbecker** [comment]
ping @ggilmore

**Comment by ggilmore** [comment]
Sorry I missed this. You're right that it's redundant, but I don't see it
as really that big a deal for now (especially since we release so
infrequently)

**Comment by felixfbecker** [comment]
So all we need to do is revert this PR?

**Comment by ggilmore** [comment]
No, because then pushing tags to make a new release won't work.

**Comment by ggilmore** [comment]
This PR is still valuable, it just that it also builds redundant images as
you pointed out

**Pull request merged**
